version: '3'

services:

  php:
    build: ./php
    container_name: php
    hostname: php
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://nginx/status/fpm"]
    image: stolz/php
    restart: unless-stopped
    volumes:
      - ./laravel:/www
      - ./php/config:/usr/local/etc:ro
      - ./php/socket:/var/run/php
      - ./php/supervisord.conf:/etc/supervisord.conf:ro

  web:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/status/nginx"]
    image: stolz/nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./laravel:/www
      - ./nginx/config:/etc/nginx:ro
      - ./php/socket:/var/run/php

  db:
    container_name: postgres
    hostname: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data

  cache:
    container_name: redis
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
