version: '3'

services:

  php:
    build: ./php
    container_name: php
    image: custom/php
    restart: unless-stopped
    volumes:
      - ./php/config:/usr/local/etc:ro
      - ./php/supervisord.conf:/etc/supervisord.conf:ro
      - ./laravel:/www

  web:
    build: ./nginx
    container_name: nginx
    image: custom/nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/config:/etc/nginx:ro
      - ./laravel:/www

  db:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data

  cache:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
